# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI INTERFACE.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 621)
        MainWindow.setMinimumSize(QtCore.QSize(1200, 0))
        MainWindow.setMaximumSize(QtCore.QSize(1200, 621))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.verticalLayout_5.addWidget(self.widget)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setMinimumSize(QtCore.QSize(150, 0))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.inner_rotor_radius_ui = QtWidgets.QLineEdit(self.tab)
        self.inner_rotor_radius_ui.setMaximumSize(QtCore.QSize(300, 16777215))
        self.inner_rotor_radius_ui.setStyleSheet("QLineEdit{\n"
"  width: 100%;\n"
"  padding: 5px;\n"
"  border: 1px solid #ccc;\n"
"  border-radius: 3px;\n"
"  font-size: 12px;\n"
"}\n"
"QLineEdit:focus {\n"
"border-color: #66afe9;\n"
"outline : 0;\n"
"}")
        self.inner_rotor_radius_ui.setAlignment(QtCore.Qt.AlignCenter)
        self.inner_rotor_radius_ui.setObjectName("inner_rotor_radius_ui")
        self.horizontalLayout_5.addWidget(self.inner_rotor_radius_ui)
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setMinimumSize(QtCore.QSize(150, 0))
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_5.addWidget(self.label_10)
        self.motor_lenght_ui = QtWidgets.QLineEdit(self.tab)
        self.motor_lenght_ui.setMaximumSize(QtCore.QSize(300, 16777215))
        self.motor_lenght_ui.setStyleSheet("QLineEdit{\n"
"  width: 100%;\n"
"  padding: 5px;\n"
"  border: 1px solid #ccc;\n"
"  border-radius: 3px;\n"
"  font-size: 12px;\n"
"}\n"
"QLineEdit:focus {\n"
"border-color: #66afe9;\n"
"outline : 0;\n"
"}")
        self.motor_lenght_ui.setAlignment(QtCore.Qt.AlignCenter)
        self.motor_lenght_ui.setObjectName("motor_lenght_ui")
        self.horizontalLayout_5.addWidget(self.motor_lenght_ui)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setMinimumSize(QtCore.QSize(150, 0))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.outer_rotor_radius_ui = QtWidgets.QLineEdit(self.tab)
        self.outer_rotor_radius_ui.setMaximumSize(QtCore.QSize(300, 16777215))
        self.outer_rotor_radius_ui.setStyleSheet("QLineEdit{\n"
"  width: 100%;\n"
"  padding: 5px;\n"
"  border: 1px solid #ccc;\n"
"  border-radius: 3px;\n"
"  font-size: 12px;\n"
"}\n"
"QLineEdit:focus {\n"
"border-color: #66afe9;\n"
"outline : 0;\n"
"}\n"
"")
        self.outer_rotor_radius_ui.setAlignment(QtCore.Qt.AlignCenter)
        self.outer_rotor_radius_ui.setObjectName("outer_rotor_radius_ui")
        self.horizontalLayout_4.addWidget(self.outer_rotor_radius_ui)
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setMinimumSize(QtCore.QSize(150, 0))
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_4.addWidget(self.label_11)
        self.phases_ui = QtWidgets.QLineEdit(self.tab)
        self.phases_ui.setMaximumSize(QtCore.QSize(300, 16777215))
        self.phases_ui.setStyleSheet("QLineEdit{\n"
"  width: 100%;\n"
"  padding: 5px;\n"
"  border: 1px solid #ccc;\n"
"  border-radius: 3px;\n"
"  font-size: 12px;\n"
"}\n"
"QLineEdit:focus {\n"
"border-color: #66afe9;\n"
"outline : 0;\n"
"}")
        self.phases_ui.setAlignment(QtCore.Qt.AlignCenter)
        self.phases_ui.setObjectName("phases_ui")
        self.horizontalLayout_4.addWidget(self.phases_ui)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setMinimumSize(QtCore.QSize(150, 0))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.ancoche_radius_ui = QtWidgets.QLineEdit(self.tab)
        self.ancoche_radius_ui.setMaximumSize(QtCore.QSize(300, 16777215))
        self.ancoche_radius_ui.setStyleSheet("QLineEdit{\n"
"  width: 100%;\n"
"  padding: 5px;\n"
"  border: 1px solid #ccc;\n"
"  border-radius: 3px;\n"
"  font-size: 12px;\n"
"}\n"
"QLineEdit:focus {\n"
"border-color: #66afe9;\n"
"outline : 0;\n"
"}")
        self.ancoche_radius_ui.setAlignment(QtCore.Qt.AlignCenter)
        self.ancoche_radius_ui.setObjectName("ancoche_radius_ui")
        self.horizontalLayout_2.addWidget(self.ancoche_radius_ui)
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setMinimumSize(QtCore.QSize(150, 0))
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_2.addWidget(self.label_12)
        self.conducters_ui = QtWidgets.QLineEdit(self.tab)
        self.conducters_ui.setMaximumSize(QtCore.QSize(300, 16777215))
        self.conducters_ui.setStyleSheet("QLineEdit{\n"
"  width: 100%;\n"
"  padding: 5px;\n"
"  border: 1px solid #ccc;\n"
"  border-radius: 3px;\n"
"  font-size: 12px;\n"
"}\n"
"QLineEdit:focus {\n"
"border-color: #66afe9;\n"
"outline : 0;\n"
"}")
        self.conducters_ui.setAlignment(QtCore.Qt.AlignCenter)
        self.conducters_ui.setObjectName("conducters_ui")
        self.horizontalLayout_2.addWidget(self.conducters_ui)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setMinimumSize(QtCore.QSize(150, 0))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.outer_ancoche_radius_ui = QtWidgets.QLineEdit(self.tab)
        self.outer_ancoche_radius_ui.setMaximumSize(QtCore.QSize(300, 16777215))
        self.outer_ancoche_radius_ui.setStyleSheet("QLineEdit{\n"
"  width: 100%;\n"
"  padding: 5px;\n"
"  border: 1px solid #ccc;\n"
"  border-radius: 3px;\n"
"  font-size: 12px;\n"
"}\n"
"QLineEdit:focus {\n"
"border-color: #66afe9;\n"
"outline : 0;\n"
"}\n"
"")
        self.outer_ancoche_radius_ui.setAlignment(QtCore.Qt.AlignCenter)
        self.outer_ancoche_radius_ui.setObjectName("outer_ancoche_radius_ui")
        self.horizontalLayout_3.addWidget(self.outer_ancoche_radius_ui)
        self.label_13 = QtWidgets.QLabel(self.tab)
        self.label_13.setMinimumSize(QtCore.QSize(150, 0))
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_3.addWidget(self.label_13)
        self.courant_ui = QtWidgets.QLineEdit(self.tab)
        self.courant_ui.setMaximumSize(QtCore.QSize(300, 16777215))
        self.courant_ui.setStyleSheet("QLineEdit{\n"
"  width: 100%;\n"
"  padding: 5px;\n"
"  border: 1px solid #ccc;\n"
"  border-radius: 3px;\n"
"  font-size: 12px;\n"
"}\n"
"QLineEdit:focus {\n"
"border-color: #66afe9;\n"
"outline : 0;\n"
"}")
        self.courant_ui.setAlignment(QtCore.Qt.AlignCenter)
        self.courant_ui.setObjectName("courant_ui")
        self.horizontalLayout_3.addWidget(self.courant_ui)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setMinimumSize(QtCore.QSize(150, 0))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        self.magnet_radius_ui = QtWidgets.QLineEdit(self.tab)
        self.magnet_radius_ui.setMaximumSize(QtCore.QSize(300, 16777215))
        self.magnet_radius_ui.setStyleSheet("QLineEdit{\n"
"  width: 100%;\n"
"  padding: 5px;\n"
"  border: 1px solid #ccc;\n"
"  border-radius: 3px;\n"
"  font-size: 12px;\n"
"}\n"
"QLineEdit:focus {\n"
"border-color: #66afe9;\n"
"outline : 0;\n"
"}")
        self.magnet_radius_ui.setAlignment(QtCore.Qt.AlignCenter)
        self.magnet_radius_ui.setObjectName("magnet_radius_ui")
        self.horizontalLayout_6.addWidget(self.magnet_radius_ui)
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setMinimumSize(QtCore.QSize(150, 0))
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_6.addWidget(self.label_9)
        self.num_magnets_ui = QtWidgets.QLineEdit(self.tab)
        self.num_magnets_ui.setMaximumSize(QtCore.QSize(300, 16777215))
        self.num_magnets_ui.setStyleSheet("QLineEdit{\n"
"  width: 100%;\n"
"  padding: 5px;\n"
"  border: 1px solid #ccc;\n"
"  border-radius: 3px;\n"
"  font-size: 12px;\n"
"}\n"
"QLineEdit:focus {\n"
"border-color: #66afe9;\n"
"outline : 0;\n"
"}")
        self.num_magnets_ui.setAlignment(QtCore.Qt.AlignCenter)
        self.num_magnets_ui.setObjectName("num_magnets_ui")
        self.horizontalLayout_6.addWidget(self.num_magnets_ui)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_15 = QtWidgets.QLabel(self.tab)
        self.label_15.setMinimumSize(QtCore.QSize(150, 0))
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_7.addWidget(self.label_15)
        self.outer_stator_radius_ui = QtWidgets.QLineEdit(self.tab)
        self.outer_stator_radius_ui.setMaximumSize(QtCore.QSize(300, 16777215))
        self.outer_stator_radius_ui.setStyleSheet("QLineEdit{\n"
"  width: 100%;\n"
"  padding: 5px;\n"
"  border: 1px solid #ccc;\n"
"  border-radius: 3px;\n"
"  font-size: 12px;\n"
"}\n"
"QLineEdit:focus {\n"
"border-color: #66afe9;\n"
"outline : 0;\n"
"}")
        self.outer_stator_radius_ui.setAlignment(QtCore.Qt.AlignCenter)
        self.outer_stator_radius_ui.setObjectName("outer_stator_radius_ui")
        self.horizontalLayout_7.addWidget(self.outer_stator_radius_ui)
        self.label_16 = QtWidgets.QLabel(self.tab)
        self.label_16.setMinimumSize(QtCore.QSize(150, 0))
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_7.addWidget(self.label_16)
        self.num_ancoches_ui = QtWidgets.QLineEdit(self.tab)
        self.num_ancoches_ui.setMaximumSize(QtCore.QSize(300, 16777215))
        self.num_ancoches_ui.setStyleSheet("QLineEdit{\n"
"  width: 100%;\n"
"  padding: 5px;\n"
"  border: 1px solid #ccc;\n"
"  border-radius: 3px;\n"
"  font-size: 12px;\n"
"}\n"
"QLineEdit:focus {\n"
"border-color: #66afe9;\n"
"outline : 0;\n"
"}")
        self.num_ancoches_ui.setAlignment(QtCore.Qt.AlignCenter)
        self.num_ancoches_ui.setObjectName("num_ancoches_ui")
        self.horizontalLayout_7.addWidget(self.num_ancoches_ui)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.draw = QtWidgets.QPushButton(self.tab)
        self.draw.setStyleSheet("QPushButton {\n"
"  background-color: #213f98;\n"
"  color: #fff;\n"
"  padding:5 px 5px;\n"
"  border: none;\n"
"  border-radius: 3px;\n"
"  cursor: pointer;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  background-color: #2980b9;\n"
"}")
        self.draw.setObjectName("draw")
        self.verticalLayout_2.addWidget(self.draw)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 1151, 61))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_7.setMinimumSize(QtCore.QSize(0, 0))
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.meshing_degrees_ui = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.meshing_degrees_ui.setMinimumSize(QtCore.QSize(0, 0))
        self.meshing_degrees_ui.setMaximumSize(QtCore.QSize(300, 16777215))
        self.meshing_degrees_ui.setStyleSheet("QLineEdit{\n"
"  width: 100%;\n"
"  padding: 5px;\n"
"  border: 1px solid #ccc;\n"
"  border-radius: 3px;\n"
"  font-size: 12px;\n"
"}\n"
"QLineEdit:focus {\n"
"border-color: #66afe9;\n"
"outline : 0;\n"
"}")
        self.meshing_degrees_ui.setObjectName("meshing_degrees_ui")
        self.horizontalLayout.addWidget(self.meshing_degrees_ui)
        self.label_14 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_14.setMinimumSize(QtCore.QSize(0, 0))
        self.label_14.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_14.setObjectName("label_14")
        self.horizontalLayout.addWidget(self.label_14)
        self.meshing_radius_ui = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.meshing_radius_ui.setMaximumSize(QtCore.QSize(300, 16777215))
        self.meshing_radius_ui.setStyleSheet("QLineEdit{\n"
"  width: 100%;\n"
"  padding: 5px;\n"
"  border: 1px solid #ccc;\n"
"  border-radius: 3px;\n"
"  font-size: 12px;\n"
"}\n"
"QLineEdit:focus {\n"
"border-color: #66afe9;\n"
"outline : 0;\n"
"}\n"
"")
        self.meshing_radius_ui.setObjectName("meshing_radius_ui")
        self.horizontalLayout.addWidget(self.meshing_radius_ui)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.mesh = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.mesh.setStyleSheet("QPushButton {\n"
"  background-color: #213f98;\n"
"  color: #fff;\n"
"  padding:5 px 5px;\n"
"  border: none;\n"
"  border-radius: 3px;\n"
"  cursor: pointer;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  background-color: #2980b9;\n"
"}")
        self.mesh.setObjectName("mesh")
        self.verticalLayout_3.addWidget(self.mesh)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.tab_3)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(10, 10, 1161, 61))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label.setObjectName("label")
        self.horizontalLayout_15.addWidget(self.label)
        self.calculate_options = QtWidgets.QComboBox(self.verticalLayoutWidget_4)
        self.calculate_options.setObjectName("calculate_options")
        self.calculate_options.addItem("")
        self.calculate_options.addItem("")
        self.calculate_options.addItem("")
        self.calculate_options.addItem("")
        self.horizontalLayout_15.addWidget(self.calculate_options)
        self.verticalLayout_9.addLayout(self.horizontalLayout_15)
        self.calculate = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.calculate.setStyleSheet("QPushButton {\n"
"  background-color: #213f98;\n"
"  color: #fff;\n"
"  padding:5 px 5px;\n"
"  border: none;\n"
"  border-radius: 3px;\n"
"  cursor: pointer;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  background-color: #2980b9;\n"
"}")
        self.calculate.setObjectName("calculate")
        self.verticalLayout_9.addWidget(self.calculate)
        self.tabWidget.addTab(self.tab_3, "")
        self.verticalLayout_4.addWidget(self.tabWidget)
        self.picture_place = QtWidgets.QLabel(self.centralwidget)
        self.picture_place.setMinimumSize(QtCore.QSize(0, 400))
        self.picture_place.setStyleSheet("QLabel{\n"
"background-color : white\n"
"\n"
"}")
        self.picture_place.setText("")
        self.picture_place.setAlignment(QtCore.Qt.AlignCenter)
        self.picture_place.setObjectName("picture_place")
        self.verticalLayout_4.addWidget(self.picture_place)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.label_30 = QtWidgets.QLabel(self.centralwidget)
        self.label_30.setObjectName("label_30")
        self.verticalLayout_5.addWidget(self.label_30)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 21))
        self.menubar.setObjectName("menubar")
        self.menuA2 = QtWidgets.QMenu(self.menubar)
        self.menuA2.setObjectName("menuA2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionCaractirestiques = QtWidgets.QAction(MainWindow)
        self.actionCaractirestiques.setObjectName("actionCaractirestiques")
        self.actionReseaux = QtWidgets.QAction(MainWindow)
        self.actionReseaux.setObjectName("actionReseaux")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.menuA2.addAction(self.actionClose)
        self.menubar.addAction(self.menuA2.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ENP ME"))
        self.label_4.setText(_translate("MainWindow", "Inner rotor radius"))
        self.label_10.setText(_translate("MainWindow", "Motor lenght "))
        self.label_3.setText(_translate("MainWindow", "Outer rotor radius"))
        self.label_11.setText(_translate("MainWindow", "Phases"))
        self.label_6.setText(_translate("MainWindow", "Ancoche radius"))
        self.label_12.setText(_translate("MainWindow", "Conducters"))
        self.label_2.setText(_translate("MainWindow", "Outer ancoche radius"))
        self.label_13.setText(_translate("MainWindow", "Courant"))
        self.label_5.setText(_translate("MainWindow", "Magnet radius"))
        self.label_9.setText(_translate("MainWindow", "Num magnets"))
        self.label_15.setText(_translate("MainWindow", "Outer stator radius"))
        self.label_16.setText(_translate("MainWindow", "Num ancoches"))
        self.draw.setText(_translate("MainWindow", "Draw"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Configuration"))
        self.label_7.setText(_translate("MainWindow", "Meshing degrees"))
        self.label_14.setText(_translate("MainWindow", "Meshing radius"))
        self.mesh.setText(_translate("MainWindow", "Mesh"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Meshing"))
        self.label.setText(_translate("MainWindow", "Operations"))
        self.calculate_options.setItemText(0, _translate("MainWindow", "FMM"))
        self.calculate_options.setItemText(1, _translate("MainWindow", "Potentiel"))
        self.calculate_options.setItemText(2, _translate("MainWindow", "Flux"))
        self.calculate_options.setItemText(3, _translate("MainWindow", "Induction"))
        self.calculate.setText(_translate("MainWindow", "Calculate"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Heat Map"))
        self.label_30.setText(_translate("MainWindow", "Devleped by: Souhaib CHERBAL, Sofiane belkbir, Mohammed siad, Salim ayad [2024]"))
        self.menuA2.setTitle(_translate("MainWindow", "File"))
        self.actionCaractirestiques.setText(_translate("MainWindow", "Caractirestiques"))
        self.actionReseaux.setText(_translate("MainWindow", "Reseaux"))
        self.actionClose.setText(_translate("MainWindow", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
